### ISSUE TITLE
Saving with values in "Issue Jql Matcher" failed

### ISSUE THREAD

**Issue by udeployuser** [mohamicorp/yet-another-commit-checker#111]
I'm getting the error "Unable to validate JQL query with JIRA because there was an unexpected exception. Please see Stash logs." when I have a simple query in Issue Jql Matcher, ie "assignee is not empty"

Error is below.  I believe my connection to Jira is fine, because I'm able to look up JIRA tickets from our commits in Stash, so I don't know why I would get the below error.

2016-06-14 16:14:05,619 ERROR [http-nio-7990-exec-28] stsai @VE26Y0x973x1006303x0 17hhpc7 172.27.216.8 "PUT /rest/api/latest/projects/TRVL/repos/test-automation/settings/hooks/com.isroot.stash.plugin.yacc%3AyaccHook/enabled HTTP/1.1" c.i.stash.plugin.ConfigValidator unexpected exception while trying to validate jql query
com.atlassian.sal.api.net.ResponseException: java.net.SocketTimeoutException: Read timed out
        at com.atlassian.sal.core.net.HttpClientRequest.executeAndReturn(HttpClientRequest.java:386) ~[sal-core-2.13.4.jar:na]
        at com.atlassian.applinks.core.auth.ApplicationLinkRequestAdaptor.executeAndReturn(ApplicationLinkRequestAdaptor.java:78) ~[na:na]
        at com.atlassian.applinks.core.auth.oauth.OAuthRequest.executeAndReturn(OAuthRequest.java:76) ~[na:na]
        at com.atlassian.applinks.core.auth.AbstractApplicationLinkRequest.execute(AbstractApplicationLinkRequest.java:159) ~[na:na]
        at com.isroot.stash.plugin.JiraServiceImpl.executeJqlQuery(JiraServiceImpl.java:147) ~[na:na]
        at com.isroot.stash.plugin.JiraServiceImpl.isJqlQueryValid(JiraServiceImpl.java:120) ~[na:na]
        at com.isroot.stash.plugin.ConfigValidator.validate(ConfigValidator.java:47) ~[na:na]
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.validateSettings(DefaultRepositoryHookService.java:501) [stash-service-impl-3.11.1.jar:na]
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.enable(DefaultRepositoryHookService.java:181) [stash-service-impl-3.11.1.jar:na]
        at com.atlassian.stash.internal.rest.repository.RepositoryHookResource.enableHook(RepositoryHookResource.java:177) [stash-rest-3.11.1.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.7_1436777144000.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:103) [atlassian-trusted-apps-core-4.0.0.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1432266788000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:36) [analytics-client-3.70.1_1436183208000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.70.1_1436183208000.jar:na]
        at com.atlassian.stash.internal.web.StreamGuardFilter.doFilter(StreamGuardFilter.java:49) [stash-stream-guard-plugin-1.0.1.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.11.1.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
        ... 259 frames trimmed
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_51]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_51]
        at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_51]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_51]
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_51]
        at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_51]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973) ~[na:1.8.0_51]
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930) ~[na:1.8.0_51]
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_51]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_51]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_51]
        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1118) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1974) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1736) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1099) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[commons-httpclient-3.1-atlassian-2.jar:na]
        at com.atlassian.sal.core.net.HttpClientRequest.executeMethod(HttpClientRequest.java:597) ~[sal-core-2.13.4.jar:na]
        at com.atlassian.sal.core.net.HttpClientRequest.executeMethod(HttpClientRequest.java:556) ~[sal-core-2.13.4.jar:na]
        at com.atlassian.sal.core.net.HttpClientRequest.executeAndReturn(HttpClientRequest.java:360) ~[sal-core-2.13.4.jar:na]
        ... 25 common frames omitted

**Comment by sford** [comment]
The key error snippet is this:

> Caused by: java.net.SocketTimeoutException: Read timed out

This indicates that at this particular time, Bitbucket Server had a problem communicating with JIRA. This could be caused by numerous things... network blip, JIRA taking a long time to respond, etc. This could just be a transient issue, but, if it is occurring frequently, I would probably start checking JIRA to make sure it is healthy.

**Comment by george-vulov** [comment]
Adding an option to tolerate Jira outages is tracked on #138. We'll also consider increasing the default timeouts.
