### ISSUE TITLE
git commit from bamboo rejecting by YACC.

### ISSUE THREAD

**Issue by dacoolfrenchie** [mohamicorp/yet-another-commit-checker#246]
Bamboo: 6.10.4
Bitbucket: 5.10.1
YACC: 1.24

When committing from my computer I see there is no issue. As show below

2020-06-05 19:12:14,449 DEBUG [io-pump:thread-47361] MeTheUser @19WR9D1x1152x1186848x1 19m1jqr 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl executing JQL query on JIRA application link 'JIRA': project = 'AP'
2020-06-05 19:12:14,526 DEBUG [io-pump:thread-47361] MeTheUser @19WR9D1x1152x1186848x1 19m1jqr 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl json response: {"expand":"schema,names","startAt":0,"maxResults":50,"total":18096,"issues":[{"expand":"operations,versionedRepresentations,editmeta,changelog,renderedFields","id":"142362","self":"https://bitbucketserverurlrest/api/2/issue/142362","key":"AP-19138","fields":{"summary":"testing bamboo"}}]}
2020-06-05 19:12:14,527 DEBUG [io-pump:thread-47361] MeTheUser @19WR9D1x1152x1186848x1 19m1jqr 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.stash.plugin.YaccServiceImpl checking JIRA issue=IssueKey{AP-19138}
2020-06-05 19:12:14,529 DEBUG [io-pump:thread-47361] MeTheUser @19WR9D1x1152x1186848x1 19m1jqr 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl number of JIRA application links: 2
2020-06-05 19:12:14,529 DEBUG [io-pump:thread-47361] MeTheUser @19WR9D1x1152x1186848x1 19m1jqr 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl executing JQL query on JIRA application link 'Cognitive Division': issueKey='AP-19138'
2020-06-05 19:12:14,584 DEBUG [io-pump:thread-47361] MeTheUser @19WR9D1x1152x1186848x1 19m1jqr 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl json response: {"startAt":0,"maxResults":50,"total":0,"issues":[]}
2020-06-05 19:12:14,585 DEBUG [io-pump:thread-47361] MeTheUser @19WR9D1x1152x1186848x1 19m1jqr 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl executing JQL query on JIRA application link 'JIRA': issueKey='AP-19138'
2020-06-05 19:12:14,617 DEBUG [io-pump:thread-47361] MeTheUser @19WR9D1x1152x1186848x1 19m1jqr 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl json response: {"expand":"names,schema","startAt":0,"maxResults":50,"total":1,"issues":[{"expand":"operations,versionedRepresentations,editmeta,changelog,renderedFields","id":"142362","self":"https://bitbucketserverurlrest/api/2/issue/142362","key":"AP-19138","fields":{"summary":"testing bamboo"}}]}

However when I do the same commit from bamboo, it's failing as seeing the project as below:

2020-06-05 19:25:36,912 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.YaccHookCommitCallback yacc commit callback, ref=refs/heads/test commit=0a0394c26400c6e213e34a0b3fb0e3a339a0d909
2020-06-05 19:25:36,912 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.stash.plugin.YaccServiceImpl checking commit id=0a0394c26400c6e213e34a0b3fb0e3a339a0d909 name=Atlassian Bamboo email=bamboo@example.com message=AP-19138 Bamboo version bump for 'test' branchName=test
2020-06-05 19:25:36,912 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.stash.plugin.YaccServiceImpl branch check, excludeBranchRegex= branchName=test
2020-06-05 19:25:36,914 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.stash.plugin.YaccServiceImpl found jira issues [IssueKey{AP-19138}] from commit message: AP-19138 Bamboo version bump for 'test'
2020-06-05 19:25:36,914 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.stash.plugin.YaccServiceImpl ignoreUnknownIssueProjectKeys=true
2020-06-05 19:25:36,916 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl number of JIRA application links: 2
2020-06-05 19:25:36,968 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl response entity: {"errorMessages":["The value 'AP' does not exist for the field 'project'."],"errors":{}}
2020-06-05 19:25:36,968 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl 400 check, false
2020-06-05 19:25:36,968 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl executing JQL query on JIRA application link 'JIRA': project = 'AP'
2020-06-05 19:25:36,988 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl status code 400
com.atlassian.sal.api.net.ResponseStatusException: Unexpected response received. Status code: 400
	at com.atlassian.applinks.core.auth.ApplicationLinksStringReturningResponseHandler.handle(ApplicationLinksStringReturningResponseHandler.java:16)
	at com.atlassian.applinks.core.auth.ApplicationLinksStringReturningResponseHandler.handle(ApplicationLinksStringReturningResponseHandler.java:13)
	at com.atlassian.applinks.oauth.auth.OAuthApplinksReturningResponseHandler.handle(OAuthApplinksReturningResponseHandler.java:48)
	at com.atlassian.sal.core.net.HttpClientRequest.executeAndReturn(HttpClientRequest.java:106)
	at com.atlassian.applinks.core.auth.ApplicationLinkRequestAdaptor.executeAndReturn(ApplicationLinkRequestAdaptor.java:53)
	at com.atlassian.applinks.oauth.auth.OAuthRequest.executeAndReturn(OAuthRequest.java:84)
	at com.atlassian.applinks.core.auth.AbstractApplicationLinkRequest.execute(AbstractApplicationLinkRequest.java:114)
	at com.isroot.stash.plugin.jira.JiraServiceImpl.execute(JiraServiceImpl.java:185)
	at com.isroot.stash.plugin.jira.JiraServiceImpl.doesProjectExist(JiraServiceImpl.java:103)
	at com.isroot.stash.plugin.YaccServiceImpl.checkJiraIssues(YaccServiceImpl.java:310)
	at com.isroot.stash.plugin.YaccServiceImpl.checkCommit(YaccServiceImpl.java:132)
	at com.isroot.stash.plugin.YaccHookCommitCallback.onCommitAdded(YaccHookCommitCallback.java:50)
	at com.atlassian.stash.internal.hook.repository.SafeRepositoryHookCommitCallback.lambda$onCommitAdded$2(SafeRepositoryHookCommitCallback.java:78)
	at com.atlassian.stash.internal.hook.repository.SafeRepositoryHookCommitCallback.invokeSafely(SafeRepositoryHookCommitCallback.java:133)
	at com.atlassian.stash.internal.hook.repository.SafeRepositoryHookCommitCallback.onCommitAdded(SafeRepositoryHookCommitCallback.java:78)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookCallbackInvoker$HookCallbackInvokingCallback.onCommit(DefaultRepositoryHookCallbackInvoker.java:316)
	at com.atlassian.stash.internal.hook.repository.CachingRepositoryHookScmHelper$CachingCommitCallback.onCommit(CachingRepositoryHookScmHelper.java:242)
	at com.atlassian.stash.internal.scm.git.command.revlist.CallbackRevListOutputHandler.processReader(CallbackRevListOutputHandler.java:86)
	at com.atlassian.bitbucket.io.LineReaderOutputHandler.process(LineReaderOutputHandler.java:42)
	at com.atlassian.bitbucket.scm.SummarizingProcessHandler$DelegatingInputStreamHandler.process(SummarizingProcessHandler.java:184)
	at com.atlassian.bitbucket.scm.SummarizingProcessHandler$DelegatingInputStreamHandler.process(SummarizingProcessHandler.java:166)
	at com.atlassian.bitbucket.scm.SummarizingProcessHandler.processOutput(SummarizingProcessHandler.java:90)
	at com.atlassian.utils.process.ExternalProcessImpl$StdoutHandler.handle(ExternalProcessImpl.java:794)
	at com.atlassian.utils.process.ExternalProcessImpl$HandlerLatchedRunnable.doTask(ExternalProcessImpl.java:731)
	at com.atlassian.utils.process.LatchedRunnable.run(LatchedRunnable.java:158)
	at com.atlassian.utils.process.ExternalProcessImpl$AsynchronousHandlerLatchedRunnable.run(ExternalProcessImpl.java:700)
	at com.atlassian.stash.internal.concurrent.DefaultTransferableStateManager$StateTransferringRunnable.run(DefaultTransferableStateManager.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(Thread.java:748)
	... 3 frames trimmed
2020-06-05 19:25:36,989 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl response entity: {"errorMessages":["The value 'AP' does not exist for the field 'project'."],"errors":{}}
2020-06-05 19:25:36,989 DEBUG [io-pump:thread-47454] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.jira.JiraServiceImpl 400 check, false
2020-06-05 19:25:36,992 DEBUG [hook-callback:thread-18] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git rev-list --format=%H%x02%P%x02%aN%x02%aE%x02%at%x02%cN%x02%cE%x02%ct%n%B%n%x03END%x04 --ignore-missing --topo-order --no-min-parents --stdin --
2020-06-05 19:25:36,992 DEBUG [hook-callback:thread-18] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.YaccHookCommitCallback callback onEnd
2020-06-05 19:25:36,992 DEBUG [hook-callback:thread-18] a015be469957d4c7 @19WR9D1x1165x1187445x0 1p9knnv 127.0.0.1 SSH - git-receive-pack '/ap/1desk-content-pack.git' c.i.s.plugin.errors.YaccErrorBuilder error type=NO_JIRA_ISSUE message=refs/heads/test: 0a0394c26400c6e213e34a0b3fb0e3a339a0d909: No JIRA Issue found in commit message

**Comment by george-vulov** [comment]
Hi @dacoolfrenchie,

Bamboo is likely committing from a service account, which doesn't have permissions to access JIRA. Can you try enabling the ["Exclude Service User Commits"](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1442119700/Yet+Another+Commit+Checker+YACC+for+Bitbucket#Exclude-Service-User-Commits) option?

**Comment by dacoolfrenchie** [comment]
but by doing this, it will "bypass" the yacc check, which would not serve the purpose. Ideally, the account that bamboo uses should get access to jira?

**Comment by george-vulov** [comment]
Please try out the "Exclude Service User Commits" option to see if it resolves -- this would confirm that bamboo is using a service account.

I agree that ideally bamboo would have access to JIRA so those commits could be checked the same as all the others, but in practice bamboo commits have a predetermined formatting, no?

You can try out the following instructions to make sure bamboo users and groups can access Jira:
https://confluence.atlassian.com/bamboo/connecting-bamboo-to-jira-for-user-management-952604122.html
