### ISSUE TITLE
NullPointerException if yaccHook is disabled in the global configuration

### ISSUE THREAD

**Issue by djlindstr** [mohamicorp/yet-another-commit-checker#72]
The pre-receive repository hook can be disabled from the "Manage add-ons" page. If I do that, a NullPointerException is thrown:

```
2015-09-14 12:07:16,990 WARN  [threadpool:thread-52] admin @6T5I3Hx727x15513x0 127.0.0.1 "POST /scm/val/repo1.git/git-receive-pack HTTP/1.1" c.a.s.i.h.DefaultBuiltInHookHandlerFactory PreReceiveHook failed, push will be rejected.
java.lang.NullPointerException: null
    at com.isroot.stash.plugin.YaccPreReceiveHook.onReceive(YaccPreReceiveHook.java:59) ~[na:na]
    at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory$1.handle(DefaultBuiltInHookHandlerFactory.java:45) ~[stash-service-impl-3.8.0.jar:na]
    at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:345) [stash-service-impl-3.8.0.jar:na]
    at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:331) [stash-service-impl-3.8.0.jar:na]
    at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:239) [stash-service-impl-3.8.0.jar:na]
    at com.atlassian.stash.internal.hook.DefaultHookService$2$1.run(DefaultHookService.java:205) [stash-service-impl-3.8.0.jar:na]
    at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:73) [stash-platform-3.8.0.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
    ... 1 frame trimmed
```

Fix: change line 59 in YaccPreReceiveHook to
        if (hook != null && hook.isEnabled() && hook.isConfigured()) {

There should be a unit test too - unfortunately I am not familiar enough with mockito to submit a complete patch. I hope the bug report is helpful anyway.

YACC version 1.7.

**Comment by sford** [comment]
@djlindstr, thanks for the find and code! I will get that fixed up, and also get a unit test around it. Thanks!

For anyone else who is having trouble disabling YACC, I think the workaround is to just clear out the settings which should effectively disable YACC.

**Comment by sford** [comment]
I am having trouble reproducing this.... pushing appears to be working when I disable YACC from the "Manage add-ons" page in my testing.

Is it possible for you to provide reproduce steps using `atlas-run` from the Atlassian SDK?

Some follow-up questions:

* what version of Stash are you using? 
* Are you pushing as a normal user or admin user? 
* Have you configured the YACC global setting?
* is the YACC hook in the repository hooks list enabled or disabled?

**Comment by djlindstr** [comment]
```
git clone https://github.com/sford/yet-another-commit-checker.git
cd yet-another-commit-checker
atlas-run
```
Open http://localhost:7990/stash/ in browser
Login to Stash GUI as admin/admin
Administration -> Manage add-ons
Expand "Yet Another Commit Checker"
Expand "13 of 13 modules enabled"
Go to "Yet Another Commit Checker (yaccHook)" and click Disable

Then clone the local repo rep_1, make a commit and push.

I found the bug in Stash 3.8.0, but I can reproduce it with Stash 3.5.1 as above. Pushing as admin, no other configuration except as mentioned.

**Comment by george-vulov** [comment]
Couldn't reproduce in the latest version of YACC.
